name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: alxcreate/app:latest
    - name: Install Yandex.Cloud CLI
      run: |
        curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - name: Authenticate with Yandex.Cloud
      run: |
        yc config set token ${{ secrets.YC_API_TOKEN }}
    - name: Get Kubernetes cluster credentials
      run: |
        CLUSTER_ID=$(yc k8s cluster list --format json | grep -o '"id": "[^"]*' | awk -F': "' '{print $2}' | tail -n 1)
        yc managed-kubernetes cluster get-credentials --id $CLUSTER_ID --external
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f https://raw.githubusercontent.com/alxcreate/kubernetes-conf/main/add-deployment.yaml
        kubectl apply -f https://raw.githubusercontent.com/alxcreate/kubernetes-conf/main/app-service.yaml
